fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "blaivas1995@gmail.com"
        sender_name: "VivaMaster"
    registration:
        confirmation:
            enabled: true
        form:
            type: App\Form\RegistrationType
